# These are customizable formats for lore placeholders
lore-format:
  durability-infinite: "Infinite"
  durability-normal: "&7{current}/{max}"

# These are customizable formats for display name placeholders
display-name-format:
  durability-infinite: "Infinite"
  durability-normal: "&7{current}"

# Changing values here will not affect older compressor tools
compressor-tool:
  # The XMaterial name of the item
  material: GOLDEN_HOE

  # How much durability does the tool have?
  # Default: infinity
  # Valid Values: 1-2000000000
  durability: infinity

  # What name should the tool have?
  # Available Placeholders: {durability}
  display-name: "&fCompressor Tool"

  # What lore should be displayed under the name of the tool?
  # Available Placeholders: {durability}
  lore:
    - "&7Right click a block with an"
    - "&7inventory to compress the "
    - "&7contents."
    - "&8&lDurability: &7{durability}"

# You can add and remove your own custom recipes as well
# Use XMaterial names, not Bukkit names
recipes:
  coal:
    input: COAL
    output: COAL_BLOCK
    amount: 9

  iron_ingot:
    input: IRON_INGOT
    output: IRON_BLOCK
    amount: 9

  lapis_lazuli:
    input: LAPIS_LAZULI
    output: LAPIS_BLOCK
    amount: 9

  gold_nugget:
    input: GOLD_NUGGET
    output: GOLD_INGOT
    amount: 9

  gold_ingot:
    input: GOLD_INGOT
    output: GOLD_BLOCK
    amount: 9

  quartz:
    input: QUARTZ
    output: QUARTZ_BLOCK
    amount: 4

  redstone:
    input: REDSTONE
    output: REDSTONE_BLOCK
    amount: 9

  diamond:
    input: DIAMOND
    output: DIAMOND_BLOCK
    amount: 9

  emerald:
    input: EMERALD
    output: EMERALD_BLOCK
    amount: 9

  # Iron Nugget was added in Minecraft 1.11
  iron_nugget:
    input: IRON_NUGGET
    output: IRON_INGOT
    amount: 9

  # Amethyst, Raw Copper, Raw Iron, Raw Gold, and Copper were added in Minecraft 1.17
  amethyst:
    input: AMETHYST_SHARD
    output: AMETHYST_BLOCK
    amount: 4

  raw_copper:
    input: RAW_COPPER
    output: RAW_COPPER_BLOCK
    amount: 9

  raw_iron:
    input: RAW_IRON
    output: RAW_IRON_BLOCK
    amount: 9

  raw_gold:
    input: RAW_GOLD
    output: RAW_GOLD_BLOCK
    amount: 9

  copper_ingot:
    input: COPPER_INGOT
    output: COPPER_BLOCK
    amount: 9
